- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Fixes #
Describe the changes you have made in this PR -
1. PR Template update
2. Contributing Guide added to wiki
> PR Template update

- README.md
> Readme update fork and star and maintainance

- README.md
> netlify badge added

- .github/workflows/codeql-analysis.yml
- .gitignore
> workflow changed

- hotelontouch/package.json
- hotelontouch/public/index.html
- hotelontouch/src/App.js
- hotelontouch/src/components/NavbarComponent.js
- hotelontouch/src/components/index.js
- hotelontouch/src/data/projectData.js
- hotelontouch/src/index.js
- hotelontouch/src/pages/HomePage.js
- hotelontouch/src/pages/index.js
- hotelontouch/yarn.lock
> project page updated

- README.md
> docs: documentation order changed

- .github/config.yml
> docs:welcome bot message edited

- .github/stale.yml
> ci:stale bot added

- .github/issue_label_bot.yaml
> issue label bot added

- hotel-restraunt-frontend/package-lock.json
- hotel-restraunt-frontend/package.json
- hotel-restraunt-frontend/src/App.js
- hotel-restraunt-frontend/src/components/Navbar.js
- hotel-restraunt-frontend/src/components/index.js
- hotel-restraunt-frontend/src/index.js
- hotel-restraunt-frontend/src/pages/HomePage.js
- hotel-restraunt-frontend/src/pages/PageOne.js
- hotel-restraunt-frontend/src/pages/PageTwo.js
- hotel-restraunt-frontend/src/pages/index.js
Fix #16 
this is my first pr, please provide any advice if done anything wrong
> setup React router and bootstrap  for hotel-restraunt-frontend

- hotelontouch/package-lock.json
- hotelontouch/package.json
- hotelontouch/src/components/AllContributors.js
- hotelontouch/src/components/index.js
- hotelontouch/src/pages/HomePage.js
Fix #35 
✅️ Created Contributor Github Profile image
✅️ Github Icon=> Clickable => Redirect to their profile
✅️ All contributors are arranged in a way that old contributors remains on top
✅️Component is made responsive to all size of screen.
Screenshots of the changes -
> Contributor section main website

- hotelontouch/src/components/AllContributors.js
- hotelontouch/src/components/index.js
- hotelontouch/src/pages/HomePage.js
- hotelontouch/yarn.lock
> Init release

- README.md
Fixes #73
- [ Added line at the end of Readme to go to wiki]
> go to wiki addition

- .github/config.yml
> typo in config.yml

- backend/app.js
- backend/model/user.model.js
- backend/package.json
Fixes for Issue #98 
As customer model has additional features than employees and admins, customer schema has been kept separate from the hotel admin and employees.
> Here's more info about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), if needed.
- [] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [] Tried Squashing the commits into one
> [Backend] Added user schema for admin, employee and customer

- hotelontouch/src/components/OpensourceProgramme.js
Fixes #72
- [x ]
- [ x] Worked on forked repo and starred the main repo
- [x ] Checked to see if a similar PR has already been opened 🤔️
- [x ] Reviewed the contributing guidelines 🔍️
- [ x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ x] Tried Squashing the commits into one
https://user-images.githubusercontent.com/67833077/111021795-ec05e400-83f4-11eb-8d9a-943c174e8404.mp4
> Enhance the we are part of section

- backend/app.js
- backend/config/swagger.js
- backend/controller/user.controller.js
- backend/model/user.model.js
- backend/package.json
- backend/route/SampleRoute.js
- backend/route/index.js
- backend/route/user.route.js
Fixes #101 
- register as customer or staff
- login as customer or staff
- fetch all customers
- fetch all staff
- fetch user by id or by email or by phone number
- A separate `/docs` route has been created where all API descriptions are available along with success response body.
**User Registration** - other routes have been tested as well
<kbd>
</kbd>
**API Documentation** - as seen under `/docs` route
<kbd>
</kbd>
> [Backend] Basic user endpoints added

- backend/model/service.model.js
> Services model added

- hotelontouch/package.json
- hotelontouch/src/App.css
- hotelontouch/src/components/SystemFeature.js
Jumbotron was having minimal styling soo added some styling to it and its contents.
This will fix issue #104
Fixes #
1. Add the card type shadow effect to the jumbotron
2. Add Typing effect to the header of the jumbotron for laptop/desktop screen
3. Change the button color to black(so the GitHub can look better)
4. found the text on the button having spelling mistake so just fixed that(not mentioned in commit as it was a very minor change
**Added two libraries to package.json (react-socks) and (react-typewriter). 
[https://drive.google.com/file/d/1DXyxdoeXY1zcAcmexaRzuCgOQmNZibbS/view?usp=sharing](url)
> feat: Add style to jumbotron

- hotelontouch/public/index.html
- hotelontouch/src/App.js
Fixes #94 
This PR is For Adding Dark mode UI to the customer end of the Webpage
**what all has been done in this pull request**
Added Toggle for dark / light theme modes
**File Changes**
directory : hotelontouch ->src -> App.js
public -> index.html
**Preview Link**
https://deploy-preview-128--hotelontouch.netlify.app/
> ADDED Dark Mode

- backend/middlewares/user.auth.js
- backend/model/service.model.js
Fixes #131 
> Note: Work was done on a new branch from PR #121 . Merging this PR will merge #121 automatically.
> Middleware for user authentication added

- hotelontouch/src/App.js
- hotelontouch/src/components/NavbarComponent.js
Fixes #
-  Created a new folder constants in hotelontouch/src , and a new file constants/routes.js in it 
-  In constants/routes.js , added path for home page and contact page
-  In App.js, instead of hard path, added reference path
-  In NavbarComponent.js, Converted Navbar.Brand and NavDropdown.Item as react-router-dom Link .
> fix: Fix reloading problem of different paths

- hotelontouch/src/components/SystemFeature.js
> systemFeature-bugs-fixed
